name: Recent Activity

on:
  schedule:
    - cron: "0 * * * *"   # Runs every hour
  workflow_dispatch:       # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update README with recent activity
        uses: Readme-Workflows/recent-activity@v2.3.0   # ✅ exact version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
